baseurl: http://www.skintdance.org.uk
# baseurl: http://localhost:1313
name: "Skint Dance"
title: "Skint Dance"
theme: skint-theme

params:
  googleAnalytics: ""

disableKinds: ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
